### ISSUE TITLE
a request for  the inference code

### ISSUE THREAD

**Issue by wdrink** [NeuralVFX/faceswap-autoencoder#2]
Thanks a lot for your fantastic work. Could you please provide the inference code?

**Comment by NeuralVFX** [comment]
I've updated the repo adding a couple of new things.

These are modules for inference based on Shaoanlu's repo, except converted to Pytorch:

- converter/
- detector/

And this is a notebook which illustrates how to load an already trained model and perform inference:

- inference.ipynb

Just like Shaoanlu's version, it takes a .mp4 video as input and outputs the same.


I'm not sure if this is exactly what you were looking for, however, it's what I used to perform inference on my tests.

Just an FYI, in my tests I've noticed that the automatic masking works better on some clips than others, so I recommend using multiple clips from different angles to evaluate the results.

**Comment by wdrink** [comment]
ok, thanks a lot.
